spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=task_db;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Ariel@Password123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

server.port=8080

app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250655368566D5970337336763979244226452948404D635162546A576E5A7234753778214125442A
app.jwt.expiration-ms=86400000
